// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type LogInfo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Msec                 int64    `protobuf:"varint,2,opt,name=msec,proto3" json:"msec,omitempty"`
	UserIp               string   `protobuf:"bytes,3,opt,name=userIp,proto3" json:"userIp,omitempty"`
	Exception            string   `protobuf:"bytes,4,opt,name=exception,proto3" json:"exception,omitempty"`
	TimeSpan             string   `protobuf:"bytes,5,opt,name=timeSpan,proto3" json:"timeSpan,omitempty"`
	Level                string   `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	Logger               string   `protobuf:"bytes,7,opt,name=logger,proto3" json:"logger,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	LogType              string   `protobuf:"bytes,9,opt,name=logType,proto3" json:"logType,omitempty"`
	TraceId              string   `protobuf:"bytes,10,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInfo) Reset()         { *m = LogInfo{} }
func (m *LogInfo) String() string { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()    {}
func (*LogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{0}
}

func (m *LogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInfo.Unmarshal(m, b)
}
func (m *LogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInfo.Marshal(b, m, deterministic)
}
func (m *LogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfo.Merge(m, src)
}
func (m *LogInfo) XXX_Size() int {
	return xxx_messageInfo_LogInfo.Size(m)
}
func (m *LogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfo proto.InternalMessageInfo

func (m *LogInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LogInfo) GetMsec() int64 {
	if m != nil {
		return m.Msec
	}
	return 0
}

func (m *LogInfo) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

func (m *LogInfo) GetException() string {
	if m != nil {
		return m.Exception
	}
	return ""
}

func (m *LogInfo) GetTimeSpan() string {
	if m != nil {
		return m.TimeSpan
	}
	return ""
}

func (m *LogInfo) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *LogInfo) GetLogger() string {
	if m != nil {
		return m.Logger
	}
	return ""
}

func (m *LogInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *LogInfo) GetLogType() string {
	if m != nil {
		return m.LogType
	}
	return ""
}

func (m *LogInfo) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

// The response message containing the greetings.
type LogInfoResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInfoResponse) Reset()         { *m = LogInfoResponse{} }
func (m *LogInfoResponse) String() string { return proto.CompactTextString(m) }
func (*LogInfoResponse) ProtoMessage()    {}
func (*LogInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{1}
}

func (m *LogInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInfoResponse.Unmarshal(m, b)
}
func (m *LogInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInfoResponse.Marshal(b, m, deterministic)
}
func (m *LogInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInfoResponse.Merge(m, src)
}
func (m *LogInfoResponse) XXX_Size() int {
	return xxx_messageInfo_LogInfoResponse.Size(m)
}
func (m *LogInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogInfoResponse proto.InternalMessageInfo

func (m *LogInfoResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *LogInfoResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type FilterDataRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterDataRequest) Reset()         { *m = FilterDataRequest{} }
func (m *FilterDataRequest) String() string { return proto.CompactTextString(m) }
func (*FilterDataRequest) ProtoMessage()    {}
func (*FilterDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{2}
}

func (m *FilterDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterDataRequest.Unmarshal(m, b)
}
func (m *FilterDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterDataRequest.Marshal(b, m, deterministic)
}
func (m *FilterDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterDataRequest.Merge(m, src)
}
func (m *FilterDataRequest) XXX_Size() int {
	return xxx_messageInfo_FilterDataRequest.Size(m)
}
func (m *FilterDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterDataRequest proto.InternalMessageInfo

func (m *FilterDataRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FilterDataRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *FilterDataRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type FilterDataResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterDataResponse) Reset()         { *m = FilterDataResponse{} }
func (m *FilterDataResponse) String() string { return proto.CompactTextString(m) }
func (*FilterDataResponse) ProtoMessage()    {}
func (*FilterDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{3}
}

func (m *FilterDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterDataResponse.Unmarshal(m, b)
}
func (m *FilterDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterDataResponse.Marshal(b, m, deterministic)
}
func (m *FilterDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterDataResponse.Merge(m, src)
}
func (m *FilterDataResponse) XXX_Size() int {
	return xxx_messageInfo_FilterDataResponse.Size(m)
}
func (m *FilterDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterDataResponse proto.InternalMessageInfo

func (m *FilterDataResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *FilterDataResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*LogInfo)(nil), "pb.v1.LogInfo")
	proto.RegisterType((*LogInfoResponse)(nil), "pb.v1.LogInfoResponse")
	proto.RegisterType((*FilterDataRequest)(nil), "pb.v1.FilterDataRequest")
	proto.RegisterType((*FilterDataResponse)(nil), "pb.v1.FilterDataResponse")
}

func init() { proto.RegisterFile("logger.proto", fileDescriptor_d43b7bfc6b6f7b16) }

var fileDescriptor_d43b7bfc6b6f7b16 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbd, 0x8e, 0xd3, 0x40,
	0x10, 0xc7, 0xb1, 0x13, 0x3b, 0x97, 0xd1, 0xf1, 0xb5, 0x42, 0xa7, 0xc5, 0x3a, 0xd0, 0xc9, 0x34,
	0x27, 0x0a, 0x1b, 0x43, 0x07, 0x1d, 0x20, 0xa4, 0x48, 0x81, 0xc2, 0x39, 0x51, 0xd0, 0xed, 0x39,
	0xc3, 0xca, 0x92, 0xed, 0x5d, 0x76, 0x37, 0x16, 0xb4, 0xb4, 0x94, 0xbc, 0x03, 0x2f, 0xc4, 0x2b,
	0xf0, 0x20, 0x68, 0x3f, 0x4c, 0x12, 0x41, 0x49, 0x37, 0xff, 0xf9, 0x8f, 0xe6, 0xe3, 0xb7, 0x0b,
	0xa7, 0x9d, 0xe0, 0x1c, 0x55, 0x21, 0x95, 0x30, 0x82, 0x24, 0xf2, 0xba, 0x18, 0xab, 0xec, 0x9c,
	0x0b, 0xc1, 0x3b, 0x2c, 0x99, 0x6c, 0x4b, 0x36, 0x0c, 0xc2, 0x30, 0xd3, 0x8a, 0x41, 0xfb, 0xa2,
	0xfc, 0x5b, 0x0c, 0x8b, 0xb5, 0xe0, 0xab, 0xe1, 0xa3, 0x20, 0x14, 0x16, 0x3d, 0x6a, 0xcd, 0x38,
	0xd2, 0xe8, 0x22, 0xba, 0x5c, 0xd6, 0x93, 0x24, 0x04, 0xe6, 0xbd, 0xc6, 0x86, 0xc6, 0x17, 0xd1,
	0xe5, 0xac, 0x76, 0x31, 0x39, 0x83, 0x74, 0xa7, 0x51, 0xad, 0x24, 0x9d, 0xb9, 0xe2, 0xa0, 0xc8,
	0x39, 0x2c, 0xf1, 0x73, 0x83, 0xd2, 0x4e, 0xa1, 0x73, 0x67, 0xed, 0x13, 0x24, 0x83, 0x13, 0xd3,
	0xf6, 0xb8, 0x91, 0x6c, 0xa0, 0x89, 0x33, 0xff, 0x68, 0x72, 0x0f, 0x92, 0x0e, 0x47, 0xec, 0x68,
	0xea, 0x0c, 0x2f, 0xec, 0x1c, 0x7f, 0x16, 0x5d, 0xf8, 0x39, 0x5e, 0x91, 0x87, 0x00, 0x8d, 0x42,
	0x66, 0xf0, 0xaa, 0xed, 0x91, 0x9e, 0x38, 0xef, 0x20, 0x63, 0xaf, 0xe9, 0x04, 0xbf, 0xfa, 0x22,
	0x91, 0x2e, 0xfd, 0x35, 0x41, 0x5a, 0xc7, 0x28, 0xd6, 0xe0, 0x6a, 0x4b, 0xc1, 0x3b, 0x41, 0xe6,
	0x1b, 0xb8, 0x1d, 0x60, 0xd4, 0xa8, 0xa5, 0x18, 0x34, 0xba, 0x73, 0x94, 0x12, 0xea, 0x95, 0xd8,
	0x7a, 0x2c, 0x49, 0xbd, 0x4f, 0x90, 0x1c, 0x4e, 0x9d, 0x78, 0x1b, 0xb8, 0xc5, 0xae, 0xdf, 0x51,
	0x2e, 0xdf, 0xc0, 0xdd, 0x37, 0x6d, 0x67, 0x50, 0xbd, 0x66, 0x86, 0xd5, 0xf8, 0x69, 0x87, 0xda,
	0x90, 0x3b, 0x30, 0xdb, 0xa9, 0x2e, 0x70, 0xb6, 0xa1, 0xdd, 0x8a, 0x49, 0xf9, 0x8e, 0xf5, 0x53,
	0x97, 0x49, 0x5a, 0xfa, 0x5b, 0x66, 0x58, 0xe0, 0xec, 0xe2, 0xfc, 0x3d, 0x90, 0xc3, 0xa6, 0xff,
	0x6b, 0xd9, 0xa7, 0x3f, 0x22, 0x48, 0xd7, 0x1e, 0x70, 0x05, 0x89, 0x25, 0xf1, 0x84, 0xdc, 0x2a,
	0xdc, 0x4f, 0x2a, 0x02, 0x9a, 0xec, 0xec, 0x58, 0x4f, 0xd3, 0xf3, 0x1b, 0xa4, 0x85, 0x9b, 0x6b,
	0xc1, 0xf7, 0x8b, 0x11, 0x1a, 0x4a, 0xff, 0x02, 0x90, 0xdd, 0xff, 0x87, 0x13, 0xfa, 0x3c, 0xfa,
	0xfa, 0xf3, 0xd7, 0xf7, 0xf8, 0x41, 0x4e, 0xcb, 0xb1, 0x2a, 0xfd, 0x6b, 0x97, 0x47, 0x6d, 0x9f,
	0x47, 0x8f, 0x5f, 0xa6, 0x1f, 0xe6, 0xc5, 0x8b, 0xb1, 0xba, 0x4e, 0xdd, 0x3f, 0x7e, 0xf6, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0xae, 0x58, 0x16, 0xfc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	// Sends a greeting
	Info0(ctx context.Context, in *LogInfo, opts ...grpc.CallOption) (*LogInfoResponse, error)
	LogFilterData(ctx context.Context, in *FilterDataRequest, opts ...grpc.CallOption) (*FilterDataResponse, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) Info0(ctx context.Context, in *LogInfo, opts ...grpc.CallOption) (*LogInfoResponse, error) {
	out := new(LogInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.v1.Logger/Info0", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogFilterData(ctx context.Context, in *FilterDataRequest, opts ...grpc.CallOption) (*FilterDataResponse, error) {
	out := new(FilterDataResponse)
	err := c.cc.Invoke(ctx, "/pb.v1.Logger/LogFilterData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	// Sends a greeting
	Info0(context.Context, *LogInfo) (*LogInfoResponse, error)
	LogFilterData(context.Context, *FilterDataRequest) (*FilterDataResponse, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) Info0(ctx context.Context, req *LogInfo) (*LogInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info0 not implemented")
}
func (*UnimplementedLoggerServer) LogFilterData(ctx context.Context, req *FilterDataRequest) (*FilterDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogFilterData not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_Info0_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).Info0(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.v1.Logger/Info0",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).Info0(ctx, req.(*LogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogFilterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogFilterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.v1.Logger/LogFilterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogFilterData(ctx, req.(*FilterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.v1.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info0",
			Handler:    _Logger_Info0_Handler,
		},
		{
			MethodName: "LogFilterData",
			Handler:    _Logger_LogFilterData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger.proto",
}
